### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by adlaonmd**
Just the scaffold of a skeleton Docusaurus website with TypeScript https://docusaurus.io/docs/installation#scaffold-project-website

### CODE REVIEW

**Comment by adlaonmd** [comment]
I do not have the ability to assign this to you @m10rten I believe. I'll mention you instead.

**Comment by m10rten** [comment]
> I do not have the ability to assign this to you @m10rten I believe. I'll mention you instead.

Alright, you can assign me, this works too.

Do you use a .gitignore? 
Seems the node_modules seems included.

Get the Node gitignore.
Or check out in any other code project for the .gitignore .

**Comment by m10rten** [comment]
Also the readme should have the original readme content.

**Comment by adlaonmd** [comment]
That's embarrassing. I expected the .gitignore that came with the Docusaurus installation would take care of everything and not include the node_modules lol.
EDIT: Wait, node_modules is not included in the repo.

Ok, I'll keep the original readme.

**Comment by m10rten** [comment]
Node modules are excluded, my bad.

1 thing I do notice is the tsconfig being from docusaurus, could you use the settings from all projects, can be found in cm-api or validate or types or core etc etc.

**Comment by adlaonmd** [comment]
Sure, will also take a look into that tsconfig.

**Comment by adlaonmd** [comment]
Brought back the original readme.md file and copied over the tsconfig from other projects. Changed the "exclude" property to "/build" because that's where the build script goes after running. Let me know what needs to be corrected. I haven't touched tsconfig files before.

**Pull request closed without merging**
